services:
  db:
    image: postgres:16-alpine
    container_name: embypanel-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-embypanel}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-embypanel}
      POSTGRES_DB: ${POSTGRES_DB:-embypanel}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: embypanel-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD:-embypanel}" ]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./data/redis:/data

  web:
    image: embypanel-app:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_VERSION: ${NEXT_PUBLIC_APP_VERSION:-v00.00.00}
    container_name: embypanel-web
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-embypanel}:${POSTGRES_PASSWORD:-embypanel}@db:5432/${POSTGRES_DB:-embypanel}
      REDIS_URL: ${REDIS_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      EMBYPANEL_ENCRYPTION_KEY: ${EMBYPANEL_ENCRYPTION_KEY}
      INTERNAL_JOBS_SECRET: ${INTERNAL_JOBS_SECRET}
    ports:
      - "${WEB_PORT:-3000}:3000"
    volumes:
      - ./data/uploads:/app/public/uploads
    depends_on:
      - db
      - redis

  worker:
    image: embypanel-app:latest
    container_name: embypanel-worker
    restart: unless-stopped
    environment:
      NODE_ENV: production
      REDIS_URL: ${REDIS_URL}
      INTERNAL_JOBS_SECRET: ${INTERNAL_JOBS_SECRET}
      WEB_INTERNAL_URL: http://web:3000
    command: ["node", "scripts/worker-anomaly-scan.js"]
    depends_on:
      - redis
      - web

# No named volumes (we use bind mounts under ./data)
