ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "syncPasswordEnc" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "syncPasswordIv"  TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "syncPasswordTag" TEXT;
